### ISSUE TITLE
Is there a way to create two syncs?

### ISSUE THREAD

**Issue by FaTKaTz3** [userdocs/LFTP4WIN-CORE#2]
I am looking for a way to create 2 sync scripts. I want it to sync a TV folder and a Movies folder. 

But when I create the lftpsync script it deletes the other task and overwrites the script.

**Comment by userdocs** [comment]
No, the script can only generate and manage a single sync script and task instance. There is an alternate approach to this problem.

You can create a folder and use symlinks to mirror whatever you want.

~~~
mkdir -p ~/example
ln -fsn ~/my/first/download/dir ~/example/new_symlink1
ln -fsn ~/my/second/download/dir ~/example/new_symlink2
~~~

Now when setting sync script edit the custom command field and make sure you set the arguments to 

~~~
-cL
~~~

![2020-03-15_09-51-26](https://user-images.githubusercontent.com/16525024/76699173-93492180-66a2-11ea-8be9-8bcea945adac.png)

And that will sync anything you put or link into that folder.

**Comment by FaTKaTz3** [comment]
I don't really understand the first part of the solution. Do I create one folder with 2 sub folders inside of it? 
And wouldn't that pull from both servers, but save in the same local directory?

**Comment by userdocs** [comment]
I created 1 folder with two symbolic links to other directories on the same server. I am now syncing anything i add or link into that folder. There was no mention or consideration for a second server in the reply.

It's a generic sync folder.

**Comment by FaTKaTz3** [comment]
Ah I see, I guess I could also just make a folder called media with two sub directories (tv and movies). When I set up the sync script, just sync the media folder and it should just mirror into my local directory. 

I didn't think of that, but Ill have to test it when im near my computer.
