### ISSUE TITLE
Proxy support for LFTP4WIN-CORE

### ISSUE THREAD

**Issue by kamild1996** [userdocs/LFTP4WIN-CORE#5]
I can't seem to find a word about proxy support by LFTP4WIN-CORE in the docs, so I'm guessing it doesn't support it?

**Comment by userdocs** [comment]
proxy support for what?

**Comment by kamild1996** [comment]
For being able to pass the entire traffic through a defined proxy server, incl. download. WinSCP has support for it, but when using LFTP4WIN to download files, it's being ignored.

**Comment by userdocs** [comment]
It not really in the scope of he project and would be a bash/Cygwin/lftp configuration.

Lftp has some proxy settings but limited to certain protocols.

https://stackoverflow.com/questions/19751261/lftp-when-used-with-proxies-doesnt-work

https://lftp.yar.ru/lftp-man.html

And or maybe here https://github.com/userdocs/LFTP4WIN-CORE/blob/master/system/etc/lftp.conf#L32
