### ISSUE TITLE
mirror-to-local Speeds Not Matching pget-to-local

### ISSUE THREAD

**Issue by ElementalCrisis** [userdocs/LFTP4WIN-CORE#7]
Hello,

Apologies for previously creating an issue in the other repo, I missed the pinned note. 

I've noticed some weird behavior when downloading files via mirror-to-local, it's downloading a lot slower than pget-to-local. I tested it by downloading a file within a folder using pget-to-local and the download speeds comes out to around 35-40 MBps per transfer. However, when using mirror-to-local on this folder, it won't go higher than 7-10 MBps per transfer. Resource Monitor is showing quite a few ssh.exe applications spawning when running for both pget-to-local and mirror-to-local. 

Settings file. 

```
# debug 10 -o "~/lftp-debug.log"
set bmk:save-passwords true
set cache:enable no
set cmd:default-protocol sftp
set cmd:move-background true
set cmd:move-background-detach true
set cmd:parallel 1
set cmd:prompt "lftp \\[\\e[01;32m\\]\\h\\[\\e[00m\\]:\\[\\e[01;34m\\]\\w\\[\\e[00m\\] % "
set cmd:queue-parallel 1
set color:use-color auto
set dns:cache-enable no
set dns:order "inet inet6"
set ftp:ssl-allow true
set ftp:ssl-auth TLS
set ftp:ssl-force true
set ftp:ssl-protect-data true
set ftp:ssl-protect-list true
set ftps:initial-prot P
set log:enabled no
set log:enabled/xfer no
set log:level/debug 10
set log:max-size 5M
set mirror:parallel-directories no
set mirror:parallel-transfer-count 1
set mirror:set-permissions off
set mirror:use-pget-n 50
set net:reconnect-interval-base 10
set net:timeout 10
set pget:default-n 50
set pget:min-chunk-size 50M
set sftp:auto-confirm yes
set sftp:connect-program "ssh -a -x"
set ssl:verify-certificate false
set xfer:temp-file-name *.lftp
set xfer:use-temp-file yes
```

**Comment by userdocs** [comment]
This issue was resolved though?

https://github.com/userdocs/LFTP4WIN/issues/22

**Comment by ElementalCrisis** [comment]
Previously I thought I had an issue when it turned out I just didn't know how the transfer info was displayed. For this issue, I'm referring to the speed of pget-to-local vs mirror-to-local when transferring a single file. 

It's possible I'm once again confusing myself on how the transfer info is displayed so I ran another test. Transferring the file via pget-to-local took 42 seconds while the same file when transferred using mirror-to-local took 1 minute, 30 seconds, give or take a few seconds for both. Shouldn't they be near identical? I also noticed this time, mirror-to-local reported a transfer speed of 18-20 MBps.

**Comment by userdocs** [comment]
you'd need to use the lftp-conf-override custom commands to test further.

Start with something like this

![image](https://user-images.githubusercontent.com/16525024/175808221-2091766b-1c66-4dbf-bd2f-06ae547b2870.png)

**Comment by ElementalCrisis** [comment]
Matched to the image you attached, pget-to-local took 1 Minute and 36 seconds at 12-14MBps while mirror-to-local took 1 Minute and 58 seconds at 12-13MBps.

**Comment by userdocs** [comment]
You are going to have to play with the settings and find what works best for you. Use the override for pget/mirror stuff and the conf for more advanced tweaks.

The solution does not attempt to configure or optimise your connection settings. For people who need this tool it tends to require personalised optimisation

Typically the more is splits a file the more work it does at the end to put it all back together.

**Comment by ElementalCrisis** [comment]
Makes sense, I'm just curious why its slower with mirror-to-local. I'll see if I can get its speed up.

Do you recommend changing min-chunk-size or leaving it at the default of 50MB?

**Comment by userdocs** [comment]
I don't think that is default, it should be less. You can just remove or comment out that option to use the defaults.

**Comment by ElementalCrisis** [comment]
Interesting, it also shows 50MB here. 
https://github.com/userdocs/LFTP4WIN-CORE/blob/master/system/etc/lftp.conf

**Comment by userdocs** [comment]
Those are not the lftp defaults. Those are the custom settings of this solution. The default is `set pget:min-chunk-size 1M`

You can view settings by using the terminal command and typing `lftp` then type `set -a` and it will list all settings. Those not defined in the conf will be the defaults.

**Comment by ElementalCrisis** [comment]
Ah I see, thanks for the info! 

I'll go ahead and close out this issue and keep messing around with it, thanks again!
