### ISSUE TITLE
Terminal selection box appears on every use of mirror-local and pget-to-local

### ISSUE THREAD

**Issue by Joseph011296** [userdocs/LFTP4WIN-CORE#9]
Updated to a fresh, new install and wondering if this new behavior is intended.
Each time I use mirror or pget It prompts me to select a terminal.

Looking at the command configure settings and comparing to images here on github it looks like prior versions used a check box to use conemu instead of mintty, which has been replaced by a dropdown menu here as well. Nothing changes after selecting an option in the command configure screen, it still prompts for a choice on every mirror and pget.

**Comment by userdocs** [comment]
You are supposed to do this https://userdocs.github.io/LFTP4WIN-CORE/#/commands?id=custom-command-configuration

and set the default. Then it will be that by default when you used the command. The menu is always there but you won't have to change anything.
